### ISSUE TITLE
ugit should not allow partial dynamic parameters

### ISSUE THREAD

**Issue by corbob** [StartAutomating/ugit#168]
As a git CLI veteran, I have a large amount of muscle memory. As such there are some commands that I issue the short commands for, and ugit can get in their way by PowerShell's helpfulness...

As an example: I often will do `git commit -am 'message'` to quickly generate a commit with all of the changed files. Because ugit is enhancing git and adding an `-Amend` parameter, PowerShell sees the `-am` and matches it to Amend.

uget would be hard pressed to successfully parse all possible parameter permutations (and even harder pressed to keep up with them should git add more...). Instead, it would be more reasonable to allow the user to set a list of known permutations that ugit could pass along to git unhindered.

Clear as mud?

**Comment by StartAutomating** [comment]
Retitled the issue to what needs to be done.

Essentially, rather than let Powershell's native behavior for dynamic parameter mapping do it's thing, we should be several notches smarter than that.

We already "fix" some built-in parameters, like -d, -v, -c, which would complete to -Debug, -Verbose, and -Confirm.

We may need a couple of other similar replacements for attempting to pass an inputobject or -GitArgument.

However, the brainbreaking solution to this issue is to not make a dynamic parameter in the first place, unless we're 100% sure of the match.

That is to say:

If a dynamic parameter would exist for say, git commit, it should not be mapped when passing a partial command.

Thus -am will not map to -Amend, because there will be no amend when mapping dynamic parameters for -am.
